title: Bojan Zelic
name: Bojan Zelic
email: me@bojanzelic.com
description: I'm a software, infrastructure, & security enthusiast in Phoenix, AZ.

remote_theme: jameshamann/jekyll-material-theme

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

# Settings for the porfolio section

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

skills:
  - name: AmazonWebServices
  - name: AngularJS
  - name: Apache
  - name: Debian
  - name: BitBucket
  - name: Bootstrap
  - name: Bower
  - name: Csharp
  - name: CSS3
  - name: Docker
  - name: Doctrine
  - name: Git
  - name: Grunt
  - name: Gulp
  - name: HTML5
  - name: Java
  - name: JavaScript
  - name: Laravel
  - name: Less
  - name: Linux
  - name: MySql
  - name: nginx
  - name: NodeJS
  - name: PHP
  - name: PHPStorm
  - name: Sass
  - name: Symfony
  - name: Ubuntu
  - name: Vim
  - name: VisualStudio


icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: View Project

github: https://github.com/BojanZelic

baseurl: # If your site is located at /blog or /home, change it here, otherwise leave it empty
url: https://bojanzelic.github.io/ # The URL of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

syntax_highlighting: true # include the css for syntax highlighting